"""
Characterization test for `bin/calculate-loq.py`.

Rather than asserting specific "correct" LOD/LOQ values, this test pins the
*current* behaviour of the tool to a golden snapshot of its output on a known
dataset (``data/one_protein.csv``). It is a regression tripwire: if a change
alters any peptide's figures of merit, this test fails and prints exactly which
peptide/column changed and by how much.

Use it when evaluating a change (e.g. merging a PR that rewrites the fitting or
bootstrap logic): a failure here is not automatically "bad" -- it tells you
*what* moved so you can confirm the deltas are the intended ones.

The golden snapshot in ``tests/data/golden_figuresofmerit.csv`` is generated by
running the current code on the sample dataset:

    python bin/calculate-loq.py data/one_protein.csv \
        data/filename2samplegroup_map.csv --plot n --bootreps 100

When an intentional change to the fitting/bootstrap math lands, review the
per-cell diff this test prints, confirm the deltas are expected, then regenerate
the snapshot to re-pin behaviour going forward:

    python tests/test_characterization.py --regen
"""

import os
import subprocess
import sys

import numpy as np
import pandas as pd
import pytest

# --- paths -------------------------------------------------------------------
HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
SCRIPT = os.path.join(REPO, "bin", "calculate-loq.py")
CURVE_DATA = os.path.join(REPO, "data", "one_protein.csv")
CONC_MAP = os.path.join(REPO, "data", "filename2samplegroup_map.csv")
GOLDEN = os.path.join(HERE, "data", "golden_figuresofmerit.csv")

# Fixed run parameters so output is reproducible across invocations.
BOOTREPS = "100"

# Numeric columns compared with tolerance; NaN/inf handled explicitly.
NUMERIC_COLS = [
    "LOD",
    "LOQ",
    "slope_linear",
    "intercept_linear",
    "intercept_noise",
    "stndev_noise",
]

# Relative tolerance for float comparison. The tool seeds numpy/random at
# import, so runs on the same code are exact; the tolerance guards only against
# platform-level floating point noise.
RTOL = 1e-6
ATOL = 0.0


def run_tool(output_dir):
    """Run calculate-loq.py on the sample dataset and return the sorted output."""
    cmd = [
        sys.executable,
        SCRIPT,
        CURVE_DATA,
        CONC_MAP,
        "--output_path",
        str(output_dir),
        "--plot",
        "n",
        "--bootreps",
        BOOTREPS,
    ]
    subprocess.run(cmd, check=True, cwd=REPO)
    out = pd.read_csv(os.path.join(str(output_dir), "figuresofmerit.csv"))
    return out.sort_values("peptide").reset_index(drop=True)


def compare(actual, golden):
    """Return a list of human-readable mismatch strings (empty == match)."""
    problems = []

    a_pep = set(actual["peptide"])
    g_pep = set(golden["peptide"])
    if a_pep != g_pep:
        missing = g_pep - a_pep
        extra = a_pep - g_pep
        if missing:
            problems.append(f"peptides missing from output: {sorted(missing)}")
        if extra:
            problems.append(f"unexpected peptides in output: {sorted(extra)}")
        return problems  # can't align columns if the peptide sets differ

    merged = pd.merge(
        golden, actual, on="peptide", suffixes=("_golden", "_actual")
    ).sort_values("peptide")

    for col in NUMERIC_COLS:
        g = merged[f"{col}_golden"].to_numpy(dtype=float)
        a = merged[f"{col}_actual"].to_numpy(dtype=float)
        # np.isclose treats inf==inf as True and inf==finite as False; NaN==NaN
        # is False unless equal_nan=True.
        ok = np.isclose(a, g, rtol=RTOL, atol=ATOL, equal_nan=True)
        for i in np.where(~ok)[0]:
            pep = merged["peptide"].iloc[i]
            problems.append(
                f"{pep} :: {col}: golden={g[i]:.6g} actual={a[i]:.6g}"
            )
    return problems


@pytest.fixture
def golden_df():
    assert os.path.exists(GOLDEN), (
        f"golden snapshot not found at {GOLDEN}; regenerate with "
        f"`python tests/test_characterization.py --regen`"
    )
    return pd.read_csv(GOLDEN).sort_values("peptide").reset_index(drop=True)


def test_figuresofmerit_matches_golden(tmp_path, golden_df):
    actual = run_tool(tmp_path)
    problems = compare(actual, golden_df)
    assert not problems, "figures of merit differ from golden snapshot:\n" + "\n".join(
        problems
    )


def _write_golden():
    """Regenerate the golden snapshot from the current code."""
    import tempfile

    with tempfile.TemporaryDirectory() as td:
        actual = run_tool(td)
    os.makedirs(os.path.dirname(GOLDEN), exist_ok=True)
    actual.to_csv(GOLDEN, index=False)
    print(f"wrote golden snapshot ({len(actual)} rows) -> {GOLDEN}")


if __name__ == "__main__":
    if "--regen" in sys.argv:
        _write_golden()
    else:
        print("run with pytest, or pass --regen to rewrite the golden snapshot")
